sudo: required
services:
  - docker

before_install:
  - docker build -t isaac/react_test -f ./ client/Dockerfile.dev ./client

sciprt:
  - docker run isaac/react_test npm test -- --coverage

  after_success:
    -docker build -t isaac/multi-client ./client
    -docker build -t isaac/multi-nginx ./nginx
    -docker build -t isaac/multi-server ./server
    -docker build -t isaac/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push isaac/multi-client
    - docker push isaac/multi-nginx
    - docker push isaac/multi-server
    - docker push isaac/multi-worker